version: "2"

run:
  timeout: 5m
  go: "1.25"

linters:
  default: standard
  enable:
    - misspell
    - unconvert
  disable:
    # Disable unparam - many false positives with interface implementations
    - unparam
  exclusions:
    presets:
      - std-error-handling
      - common-false-positives
      - legacy
    paths:
      - zz_generated\.deepcopy\.go
    rules:
      # Allow unchecked errors in test cleanup
      - path: _test\.go
        linters:
          - errcheck
      # Allow unused functions in tests (helper functions for future use)
      - path: _test\.go
        linters:
          - unused
      # Exclude staticcheck naming convention rules - must match Keycloak API JSON
      - text: "ST1000:"
        linters:
          - staticcheck
      - text: "ST1003:"
        linters:
          - staticcheck
      - text: "ST1005:"
        linters:
          - staticcheck

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/Hostzero-GmbH/keycloak-operator
