apiVersion: keycloak.hostzero.com/v1beta1
kind: ClusterKeycloakRealm
metadata:
  name: shared-realm
spec:
  clusterInstanceRef:
    name: keycloak-cluster-instance
  realmName: shared
  definition:
    enabled: true
    displayName: "Shared Realm"
